version: 0.0
os: linux
files:
  - source: /
    destination: /
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/build.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/configure_db.sh
    - location: scripts/start_server.sh
      timeout: 300
      runas: root